/*
 * $Id: AboutDialog.java,v 1.7 2004/06/30 04:16:51 eed3si9n Exp $
 * 
 * $Copyright: copyright (c) 2003, e.e d3si9n $
 * $License: 
 * This source code is part of DoubleType.
 * DoubleType is a graphical typeface designer.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This Program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * In addition, as a special exception, e.e d3si9n gives permission to
 * link the code of this program with any Java Platform that is available
 * to public with free of charge, including but not limited to
 * Sun Microsystem's JAVA(TM) 2 RUNTIME ENVIRONMENT (J2RE),
 * and distribute linked combinations including the two.
 * You must obey the GNU General Public License in all respects for all 
 * of the code used other than Java Platform. If you modify this file, 
 * you may extend this exception to your version of the file, but you are not
 * obligated to do so. If you do not wish to do so, delete this exception
 * statement from your version.
 * $
 */
package org.doubletype.ossa;

/**
 *
 * @author  e.e
 */
public class AboutDialog extends javax.swing.JDialog {
	private static final long serialVersionUID = 1L;
	
    /** Creates new form JDialog */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        m_lblVersion.setText("DoubleType " + Version.k_version);
        
        String s;
        s = "copyright (c) 2003-2004, e.e d3si9n\n"
        	+ "\n"
			+ "	This program is free software; you can redistribute it and/or modify "
			+ "it under the terms of the GNU General Public License as published by "
			+ "the Free Software Foundation; either version 2 of the License, or "
			+ "(at your option) any later version.\n"
			+ "\n"
			+ "This Program is distributed in the hope that it will be useful, "
			+ "but WITHOUT ANY WARRANTY; without even the implied warranty of "
			+ "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the "
			+ "GNU General Public License for more details.\n"
			+ "\n"
			+ "This program contains source code generated by Relaxer.\n"
			+ "\n"
			+ "This program contains source code written by "
			+ "International Business Machines Corporation and others";
		
		m_textArea.setText(s);
		m_textArea.setCaretPosition(0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        m_pnlRoot = new javax.swing.JPanel();
        m_btnOK = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_textArea = new javax.swing.JTextArea();
        m_lblVersion = new javax.swing.JLabel();

        setName("About DoubleType...");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        m_pnlRoot.setLayout(null);

        m_pnlRoot.setPreferredSize(new java.awt.Dimension(500, 200));
        m_btnOK.setFont(new java.awt.Font("Dialog", 0, 12));
        m_btnOK.setText("OK");
        m_btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnOKActionPerformed(evt);
            }
        });

        m_pnlRoot.add(m_btnOK);
        m_btnOK.setBounds(420, 160, 70, 26);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        m_textArea.setEditable(false);
        m_textArea.setLineWrap(true);
        m_textArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(m_textArea);

        m_pnlRoot.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 403, 150);

        m_lblVersion.setFont(new java.awt.Font("Dialog", 0, 12));
        m_lblVersion.setText("DoubleType 0.0.0.0");
        m_pnlRoot.add(m_lblVersion);
        m_lblVersion.setBounds(10, 10, 190, 16);

        getContentPane().add(m_pnlRoot, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void m_btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnOKActionPerformed
        closeDialog(null);
    }//GEN-LAST:event_m_btnOKActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton m_btnOK;
    private javax.swing.JLabel m_lblVersion;
    private javax.swing.JPanel m_pnlRoot;
    private javax.swing.JTextArea m_textArea;
    // End of variables declaration//GEN-END:variables
    
}
