/*
 * $Id: GuiResource_ja_JP.ja,v 1.16 2004/11/29 07:53:19 eed3si9n Exp $
 * 
 * $Copyright: copyright (c) 2003-2004, e.e d3si9n $
 * $License: 
 * This source code is part of DoubleType.
 * DoubleType is a graphical typeface designer.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This Program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * In addition, as a special exception, e.e d3si9n gives permission to
 * link the code of this program with any Java Platform that is available
 * to public with free of charge, including but not limited to
 * Sun Microsystem's JAVA(TM) 2 RUNTIME ENVIRONMENT (J2RE),
 * and distribute linked combinations including the two.
 * You must obey the GNU General Public License in all respects for all 
 * of the code used other than Java Platform. If you modify this file, 
 * you may extend this exception to your version of the file, but you are not
 * obligated to do so. If you do not wish to do so, delete this exception
 * statement from your version.
 * $
 */

package org.doubletype.ossa;

import java.util.ListResourceBundle;

/* NOTE!
 * GuiResource_ja_JP.java is generated by native2ascii.
 * DO NOT EDIT GuiResource_ja_JP.java, because changes will be lost.
 * GuiResource_ja_JP.ja is the original file in SJIS encoding.
 */

public class GuiResource_ja_JP extends ListResourceBundle {
	static final Object[][] contents = {
		{"task", "\u30bf\u30b9\u30af"},
		{"deleteObject", "\u524a\u9664\u3059\u308b"},
		{"addPoint", "\u70b9\u3092\u8ffd\u52a0\u3059\u308b"},
		{"togglePoint", "\u30aa\u30f3/\u30aa\u30d5\u30ab\u30fc\u30d6\u70b9"},
		{"addHint", "\u30d2\u30f3\u30c8\u3092\u3064\u3051\u308b"},
		{"createContour", "\u8f2a\u90ed\u3092\u4f5c\u308b"},
	    {"createModule", "\u30e2\u30b8\u30e5\u30fc\u30eb\u3092\u4f5c\u308b"},
	    {"createInclude", "\u53c2\u7167\u3092\u4f5c\u308b"},
	    {"selectNext", "\u6b21\u3092\u9078\u629e"},
	    {"toggleGridfit", "\u30aa\u30f3/\u30aa\u30d5\u30b0\u30ea\u30c3\u30c9\u70b9"},
	    {"properties", "\u30d7\u30ed\u30d1\u30c6\u30a3"},
	    {"convertControlPoint", "\u5909\u63db\u3059\u308b"},
	    {"convertContour", "\u5909\u63db\u3059\u308b"},
		
		// file menu		
		{"file", "\u30d5\u30a1\u30a4\u30eb"},
		{"new", "\u65b0\u898f\u4f5c\u6210"},
		{"newTypeface", "\u66f8\u4f53..."},
		{"addNewGlyph", "\u30b0\u30ea\u30d5..."},
		{"addEmptyGlyph", "\u7a7a\u306e\u30b0\u30ea\u30d5..."},
		{"open", "\u958b\u304f"},
		{"openTypeface", "\u66f8\u4f53..."},
		{"addExistingGlyph", "\u30b0\u30ea\u30d5..."},
		{"openBackground", "\u80cc\u666f\u753b\u50cf..."},
		{"saveGlyph", "%0\u3092\u4fdd\u5b58"},
		{"exit", "\u7d42\u4e86"},
		
		// edit menu
		{"edit", "\u7de8\u96c6"},
		{"undo", "\u5143\u306b\u623b\u3059"},
		{"redo", "\u3084\u308a\u76f4\u3059"},
		{"cut", "\u5207\u308a\u53d6\u308a"},
		{"copy", "\u30b3\u30d4\u30fc"},
		{"paste", "\u8cbc\u308a\u4ed8\u3051"},
		{"moveLeft", "\u5de6\u3078\u79fb\u52d5"},
		{"moveUp", "\u4e0a\u3078\u79fb\u52d5"},
		{"moveDown", "\u4e0b\u3078\u79fb\u52d5"},
		{"moveRight", "\u53f3\u3078\u79fb\u52d5"},
		{"delete", "\u524a\u9664"},
		
		// view menu
		{"view", "\u8868\u793a"},
		{"showBackground", "\u80cc\u666f\u753b\u50cf"},
		{"zoom", "\u30ba\u30fc\u30e0"},
		{"resolution", "\u89e3\u50cf\u5ea6"},
		
		// font size menu
		{"fontSize", "\u30b5\u30a4\u30ba"},
		
		// typeface menu
		{"typeface", "\u66f8\u4f53"},
		{"build", "TrueType \u306e\u69cb\u7bc9"},
		{"release", "\u30ea\u30ea\u30fc\u30b9\u69cb\u7bc9"},
		{"typefaceSetting", "\u30d7\u30ed\u30d1\u30c6\u30a3"},
		
		// help menu
		{"help", "\u30d8\u30eb\u30d7"},
		
		
		{"contour", "\u8f2a\u90ed"},
		{"module", "\u30e2\u30b8\u30e5\u30fc\u30eb"},
		{"include", "\u53c2\u7167"},
		{"tree", "\u30c4\u30ea\u30fc"},
		{"add", "\u8ffd\u52a0"},
		
		{"close", "\u9589\u3058\u308b"},
		{"search", "\u691c\u7d22"},
		{"example", "\u4f8b\u793a"},
		{"jis", "JIS \u30b3\u30fc\u30c9"},
		{"unicode", "Unicode"},
		{"remove", "\u524a\u9664"},
		
		{"glyph", "\u30b0\u30ea\u30d5"},
		{"wallpaper", "\u58c1\u7d19"},
		{"hint", "\u30d2\u30f3\u30c8"},
		
		{"ascender", "\u30a2\u30bb\u30f3\u30c0\u30fc\u9ad8"},
		{"descender", "\u30c7\u30a3\u30bb\u30f3\u30c0\u30fc\u6df1"},
		{"xHeight", "\u30a8\u30c3\u30af\u30b9\u9ad8"},
		{"tsb", "\u4e0a\u30d9\u30a2\u30ea\u30f3\u30b0"},
		{"bsb", "\u4e0b\u30d9\u30a2\u30ea\u30f3\u30b0"},
		{"lsb", "\u5de6\u30d9\u30a2\u30ea\u30f3\u30b0"},
		{"rsb", "\u53f3\u30d9\u30a2\u30ea\u30f3\u30b0"},
		{"baseline", "\u30d9\u30fc\u30b9\u30e9\u30a4\u30f3"},
		{"meanline", "\u30df\u30fc\u30f3\u30e9\u30a4\u30f3"},
		{"bodytop", "\u30a2\u30bb\u30f3\u30c0\u30fc\u30e9\u30a4\u30f3"},
		{"bodybottom", "\u30c7\u30a3\u30bb\u30f3\u30c0\u30fc\u30e9\u30a4\u30f3"},
		
		{"metrics", "\u6e2c\u5b9a\u57fa\u6e96"},
		{"fontInfo", "\u66f8\u4f53\u60c5\u5831"},
		{"fontFamily", "\u30d5\u30a9\u30f3\u30c8\u30d5\u30a1\u30df\u30ea\u30fc"},
		{"copyrightInfo", "\u8457\u4f5c\u6a29\u60c5\u5831"},
		{"author", "\u4f5c\u8005\u540d"},
		{"year", "\u5236\u4f5c\u5e74"},
		{"license", "\u30e9\u30a4\u30bb\u30f3\u30b9"},
		{"codePages", "\u30b3\u30fc\u30c9\u30da\u30fc\u30b8"},
		{"glyphName", "\u30b0\u30ea\u30d5\u540d"},
		{"width", "\u30bb\u30c3\u30c8\u5e45"},
		{"bodySize", "\u30dc\u30c7\u30a3\u30fc\u30b5\u30a4\u30ba"},

		{"reference", "\u53c2\u8003"},
		{"target", "\u30bf\u30fc\u30b2\u30c3\u30c8"},
		{"fontSample", "\u30d5\u30a9\u30f3\u30c8\u898b\u672c"},
		{"glyphTable", "\u30b0\u30ea\u30d5\u8868"},
		{"typefaceFileName",			"\u66f8\u4f53\u30d5\u30a1\u30a4\u30eb\u540d"},
		{"typefaceDir",					"\u66f8\u4f53\u30d5\u30a9\u30eb\u30c0"},
		{"fileName",					"\u30d5\u30a1\u30a4\u30eb\u540d"},
		{"msgIsRequired",				"%s\u3092\u5165\u529b\u3057\u3066\u4e0b\u3055\u3044"},
		{"msgTypefaceExistsInDir",		"\u6307\u5b9a\u3055\u308c\u305f\u30d5\u30a9\u30eb\u30c0\u306b\u306f\u65e2\u306b\u66f8\u4f53\u304c\u3042\u308a\u307e\u3059"},
		
		{"pickMenu", "\u9078\u629e"},
		{"moveMenu", "\u79fb\u52d5"},
		{"addMenu", "\u8ffd\u52a0"},
		{"removeMenu", "\u524a\u9664"},
		{"includeMenu", "\u53c2\u7167"},
		{"contourMenu", "\u8f2a\u90ed"},
		{"moduleMenu", "\u30e2\u30b8\u30e5\u30fc\u30eb"},
		{"pointMenu", "\u70b9"},
		{"previewMenu", "\u30d7\u30ea\u30f4\u30e5\u30fc"},
		{"pickpoint", "\u70b9\u3092\u9078\u629e"},
		{"movepoint", "\u70b9\u3092\u79fb\u52d5"},
		{"removepoint", "\u70b9\u3092\u524a\u9664"},
		
		{"msgSaveChange",
				"\u672a\u4fdd\u5b58\u306e\u5909\u66f4\u3092\u4fdd\u5b58\u3057\u307e\u3059\u304b?"},
		{"msgAlreadyExists",
					" \u306f\u65e2\u306b\u5b58\u5728\u3057\u307e\u3059!"},
		{"msgNoTypeface",
					"\u66f8\u4f53\u304c\u3042\u308a\u307e\u305b\u3093!"},
		{"msgEmptyGlyphTitle",
					"\u30b0\u30ea\u30d5\u540d\u304c\u7a7a\u767d\u3067\u3059!"},
		{"msgUnicode",
		"\u30e6\u30cb\u30b3\u30fc\u30c9\u3092\u5165\u529b\u3057\u3066\u4e0b\u3055\u3044:\n"
		+ "\"0061\" \u306e\u3088\u3046\u306b\u5341\u516d\u9032\u6570\u3067\u5165\u529b\u3059\u308b\u304b\n" 
		+ "\"a\" \u306e\u3088\u3046\u306b\u5b9f\u969b\u306e\u6587\u5b57\u3092\u5165\u529b\u3059\u308b\u3053\u3068\u304c\u3067\u304d\u307e\u3059\u3002"
		},
		{"msgJis",
		"JIS\u5341\u516d\u9032\u30b3\u30fc\u30c9\u3092\u5165\u529b\u3057\u3066\u4e0b\u3055\u3044:\n"
		+ "\"306c\" \u306e\u3088\u3046\u306b\u5341\u516d\u9032\u6570\u3067\u5165\u529b\u3059\u308b\u304b\n" 
		+ "\"\u4e00\" \u306e\u3088\u3046\u306b\u5b9f\u969b\u306e\u6587\u5b57\u3092\u5165\u529b\u3059\u308b\u3053\u3068\u304c\u3067\u304d\u307e\u3059\u3002"
		},
		{"msgNoPunct",
		"\u534a\u89d2\u8a18\u53f7\u3092\u4f7f\u3046\u3053\u3068\u306f\u3067\u304d\u307e\u305b\u3093!\n"
		+ "(\u305f\u3060\u3057\u3001\u30de\u30a4\u30ca\u30b9\u3001\u30a2\u30f3\u30c0\u30fc\u30b9\u30b3\u30a2\u3068\u30d4\u30ea\u30aa\u30c9\u3092\u9664\u304f)"},
		{"msgGlyphName",
		"\u30b0\u30ea\u30d5\u540d\u3092\u5165\u529b\u3057\u3066\u4e0b\u3055\u3044\u3002"},
		{"msgCreateNewGlyph",
		"\u30d5\u30a1\u30a4\u30eb\u306f\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3067\u3057\u305f\u3002\n"
		+ "\u65b0\u3089\u3057\u3044\u30b0\u30ea\u30d5\u3092\u4f5c\u308a\u307e\u3059\u304b?"},
		{"msgAuthor",
		"\u4f5c\u8005\u540d\u3092\u5165\u529b\u3057\u3066\u4e0b\u3055\u3044:"},
		{"msgYear", 
		"\u5236\u4f5c\u5e74\u3092\u5165\u529b\u3057\u3066\u4e0b\u3055\u3044 (\u4f8b: 2003-2004):"},
		{"msgFamily",
		"\u30d5\u30a9\u30f3\u30c8\u30d5\u30a1\u30df\u30ea\u30fc\u540d\u3092\u5165\u529b\u3057\u3066\u4e0b\u3055\u3044:"},
		{"msgCircular",
		"\u3053\u306e\u53c2\u7167\u3092\u8ffd\u52a0\u3059\u308b\u3068\u5faa\u74b0\u53c2\u7167\u306b\u306a\u3063\u3066\u3057\u307e\u3044\u307e\u3059!"},
		{"msgHasUnicode", "\u65b0\u3057\u3044\u30b0\u30ea\u30d5\u306f\u6587\u5b57\u3067\u3059\u304b\uff1f"}
		// END OF MATERIAL TO LOCALIZE
    };
      
	/**
	 * @see java.util.ListResourceBundle#getContents()
	 */
	protected Object[][] getContents() {
		return contents;
	}
}
