/**
* This file is generated by ant script.
*/

package org.doubletype.ossa;

/**
 *
 * @author  e.e
 */
public class Version {
	// this value is set by ant script. do not edit.
	static public String k_version = "0.2.0.63";
}
  	